/*
 * SPDX-FileCopyrightText: syuilo and misskey-project
 * SPDX-License-Identifier: AGPL-3.0-only
 */

import {
	miRepository,
	MiAbuseReportNotificationRecipient,
	MiAbuseUserReport,
	MiAccessToken,
	MiAd,
	MiAnnouncement,
	MiAnnouncementRead,
	MiAntenna,
	MiApp,
	MiAuthSession,
	MiAvatarDecoration,
	MiBlocking,
	MiBubbleGameRecord,
	MiChannel,
	MiChannelFavorite,
	MiChannelFollowing,
	MiChannelMuting,
	MiChatApproval,
	MiChatMessage,
	MiChatRoom,
	MiChatRoomInvitation,
	MiChatRoomMembership,
	MiClip,
	MiClipFavorite,
	MiClipNote,
	MiDriveFile,
	MiDriveFolder,
	MiEmoji,
	MiFlash,
	MiFlashLike,
	MiFollowing,
	MiFollowRequest,
	MiGalleryLike,
	MiGalleryPost,
	MiHashtag,
	MiInstance,
	MiMeta,
	MiModerationLog,
	MiMuting,
	MiNote,
	MiNoteDraft,
	MiNoteFavorite,
	MiNoteReaction,
	MiNoteThreadMuting,
	MiPage,
	MiPageLike,
	MiPasswordResetRequest,
	MiPoll,
	MiPollVote,
	MiPromoNote,
	MiPromoRead,
	MiRegistrationTicket,
	MiRegistryItem,
	MiRelay,
	MiRenoteMuting,
	MiRetentionAggregation,
	MiReversiGame,
	MiRole,
	MiRoleAssignment,
	MiSignin,
	MiSwSubscription,
	MiSystemAccount,
	MiSystemWebhook,
	MiUsedUsername,
	MiUser,
	MiUserIp,
	MiUserKeypair,
	MiUserList,
	MiUserListFavorite,
	MiUserListMembership,
	MiUserMemo,
	MiUserNotePining,
	MiUserPending,
	MiUserProfile,
	MiUserPublickey,
	MiUserSecurityKey,
	MiWebhook,
} from '@/models/_.js';
import { DI } from '@/di-symbols.js';
import type { DataSource, EntityTarget } from 'typeorm';
import type { DependencyContainer } from 'tsyringe';
import type { MiRepository } from '@/models/_.js';

// 旧 RepositoryModule. 各 entity に対する `getRepository(X).extend(miRepository)` を
// `DI.xxxRepository` トークンで context container に登録する。
//
// 必ず `registerGlobals` のあとに呼ぶこと (DI.db に依存)。
//
// 75 エントリ。1 行 1 エントリの表として保つ:
// [DI symbol, entity class].
// 注意: tsyringe の `useValue` は eager 評価で良い。`DataSource.getRepository(X)` は
// internal cache を引くだけなので、ここで一括 resolve しても重くない。
export function registerRepositories(c: DependencyContainer): void {
	const db = c.resolve<DataSource>(DI.db);
	const table: Array<[symbol, EntityTarget<object>]> = [
		[DI.usersRepository, MiUser],
		[DI.notesRepository, MiNote],
		[DI.announcementsRepository, MiAnnouncement],
		[DI.announcementReadsRepository, MiAnnouncementRead],
		[DI.appsRepository, MiApp],
		[DI.avatarDecorationsRepository, MiAvatarDecoration],
		[DI.noteFavoritesRepository, MiNoteFavorite],
		[DI.noteThreadMutingsRepository, MiNoteThreadMuting],
		[DI.noteReactionsRepository, MiNoteReaction],
		[DI.noteDraftsRepository, MiNoteDraft],
		[DI.pollsRepository, MiPoll],
		[DI.pollVotesRepository, MiPollVote],
		[DI.userProfilesRepository, MiUserProfile],
		[DI.userKeypairsRepository, MiUserKeypair],
		[DI.userPendingsRepository, MiUserPending],
		[DI.userSecurityKeysRepository, MiUserSecurityKey],
		[DI.userPublickeysRepository, MiUserPublickey],
		[DI.userListsRepository, MiUserList],
		[DI.userListFavoritesRepository, MiUserListFavorite],
		[DI.userListMembershipsRepository, MiUserListMembership],
		[DI.userNotePiningsRepository, MiUserNotePining],
		[DI.userIpsRepository, MiUserIp],
		[DI.usedUsernamesRepository, MiUsedUsername],
		[DI.followingsRepository, MiFollowing],
		[DI.followRequestsRepository, MiFollowRequest],
		[DI.instancesRepository, MiInstance],
		[DI.emojisRepository, MiEmoji],
		[DI.driveFilesRepository, MiDriveFile],
		[DI.driveFoldersRepository, MiDriveFolder],
		[DI.metasRepository, MiMeta],
		[DI.mutingsRepository, MiMuting],
		[DI.renoteMutingsRepository, MiRenoteMuting],
		[DI.blockingsRepository, MiBlocking],
		[DI.swSubscriptionsRepository, MiSwSubscription],
		[DI.systemAccountsRepository, MiSystemAccount],
		[DI.hashtagsRepository, MiHashtag],
		[DI.abuseUserReportsRepository, MiAbuseUserReport],
		[DI.abuseReportNotificationRecipientRepository, MiAbuseReportNotificationRecipient],
		[DI.registrationTicketsRepository, MiRegistrationTicket],
		[DI.authSessionsRepository, MiAuthSession],
		[DI.accessTokensRepository, MiAccessToken],
		[DI.signinsRepository, MiSignin],
		[DI.pagesRepository, MiPage],
		[DI.pageLikesRepository, MiPageLike],
		[DI.galleryPostsRepository, MiGalleryPost],
		[DI.galleryLikesRepository, MiGalleryLike],
		[DI.moderationLogsRepository, MiModerationLog],
		[DI.clipsRepository, MiClip],
		[DI.clipNotesRepository, MiClipNote],
		[DI.clipFavoritesRepository, MiClipFavorite],
		[DI.antennasRepository, MiAntenna],
		[DI.promoNotesRepository, MiPromoNote],
		[DI.promoReadsRepository, MiPromoRead],
		[DI.relaysRepository, MiRelay],
		[DI.channelsRepository, MiChannel],
		[DI.channelFollowingsRepository, MiChannelFollowing],
		[DI.channelFavoritesRepository, MiChannelFavorite],
		[DI.channelMutingRepository, MiChannelMuting],
		[DI.registryItemsRepository, MiRegistryItem],
		[DI.webhooksRepository, MiWebhook],
		[DI.systemWebhooksRepository, MiSystemWebhook],
		[DI.adsRepository, MiAd],
		[DI.passwordResetRequestsRepository, MiPasswordResetRequest],
		[DI.retentionAggregationsRepository, MiRetentionAggregation],
		[DI.flashsRepository, MiFlash],
		[DI.flashLikesRepository, MiFlashLike],
		[DI.rolesRepository, MiRole],
		[DI.roleAssignmentsRepository, MiRoleAssignment],
		[DI.userMemosRepository, MiUserMemo],
		[DI.chatMessagesRepository, MiChatMessage],
		[DI.chatRoomsRepository, MiChatRoom],
		[DI.chatRoomMembershipsRepository, MiChatRoomMembership],
		[DI.chatRoomInvitationsRepository, MiChatRoomInvitation],
		[DI.chatApprovalsRepository, MiChatApproval],
		[DI.bubbleGameRecordsRepository, MiBubbleGameRecord],
		[DI.reversiGamesRepository, MiReversiGame],
	];

	for (const [token, entity] of table) {
		const repo = db.getRepository(entity).extend(miRepository as MiRepository<object>);
		c.register(token, { useValue: repo });
	}
}
